### ISSUE TITLE
thx

### ISSUE THREAD

**Issue by yilucode** [vpnguy-zz/snmpdos#1]
data = "\x30\x37\x02\x01" #snmp
data += "\x01" #v2
data += "\x04\x06\x70\x75\x62\x6c\x69\x63" #community=public
data += "\xa5\x2a\x02\x04\x06\x29\x07\x31\x02\x01\x00\x02\x01\x0a\x30\x1c\x30\x0b\x06\x07\x2b\x06\x01\x02\x01\x01\x01\x05\x00\x30\x0d\x06\x09\x2b\x06\x01\x02\x01\x01\x09\x01\x03\x05\x00" #getBulkRequest

it's “v2 community=public getBulkRequest”
what coding?

**Comment by vpnguy-zz** [comment]
If you're asking the encoding on the data that would be hex.
